// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------


namespace AP
{


	public partial class Default
	{

		/// <summary>
		/// Form1 элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlForm Form1;

		/// <summary>
		/// Pick элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Button Pick;

		/// <summary>
		/// spt элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox S_txt;

		/// <summary>
		/// ept элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox K_txt;

		/// <summary>
		/// rfrt элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox r_txt;

		/// <summary>
		/// sigmat элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox v_txt;

		/// <summary>
		/// timet элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox T_txt;

		/// <summary>
		/// btn1 элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Button btn1;

		/// <summary>
		/// valuecallt элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox call_txt;

		/// <summary>
		/// valueputt элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox put_txt;

		/// <summary>
		/// valuedeltacall элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox call_delta_txt;

		/// <summary>
		/// valuedeltaput элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox put_delta_txt;

		/// <summary>
		/// valuegammacall элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox call_gamma_txt;

		/// <summary>
		/// valuegammaput элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox put_gamma_txt;

		/// <summary>
		/// valuethetacall элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox call_theta_txt;

		/// <summary>
		/// valuethetaput элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox put_theta_txt;

		/// <summary>
		/// valuerhocall элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox call_rho_txt;

		/// <summary>
		/// valuerhoput элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox put_rho_txt;
	}
}
