// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------


namespace AP
{


	public partial class Default
	{

		/// <summary>
		/// Form1 элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlForm Form1;

		/// <summary>
		/// Pick элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Button Pick;

		/// <summary>
		/// spt элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox spt;

		/// <summary>
		/// ept элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox ept;

		/// <summary>
		/// rfrt элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox rfrt;

		/// <summary>
		/// sigmat элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox sigmat;

		/// <summary>
		/// timet элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox timet;

		/// <summary>
		/// btn1 элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Button btn1;

		/// <summary>
		/// valuecallt элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox valuecallt;

		/// <summary>
		/// valueputt элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox valueputt;

		/// <summary>
		/// valuedeltacall элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox valuedeltacall;

		/// <summary>
		/// valuedeltaput элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox valuedeltaput;

		/// <summary>
		/// valuegammacall элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox valuegammacall;

		/// <summary>
		/// valuegammaput элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox valuegammaput;

		/// <summary>
		/// valuethetacall элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox valuethetacall;

		/// <summary>
		/// valuethetaput элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox valuethetaput;

		/// <summary>
		/// valuerhocall элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox valuerhocall;

		/// <summary>
		/// valuerhoput элемент управления.
		/// </summary>
		/// <remarks>
		/// Автоматически создаваемое поле.
		/// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox valuerhoput;
	}
}
